# Generated by Django 4.2.2 on 2025-02-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_ingredient_recipeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='Ingredient',
            new_name='ingredient',
        ),
    ]
