# Generated by Django 4.2.2 on 2025-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_ingredient_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='単位'),
        ),
    ]
