# Generated by Django 4.2.2 on 2025-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='分量'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='分量2'),
        ),
    ]
