# Generated by Django 4.2.2 on 2025-02-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_favorite_unique_together_ingredient_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
    ]
