# Generated by Django 4.2.2 on 2025-03-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='viewd_at',
            new_name='viewed_at',
        ),
    ]
